"""empty message

Revision ID: 30826aa1efa5
Revises: cde2320c9a43
Create Date: 2024-03-05 14:51:48.298225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30826aa1efa5'
down_revision = 'cde2320c9a43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
